# Generated by Django 5.0.3 on 2025-02-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admin_worker_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='worker_images/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='worker',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='skill',
            field=models.CharField(choices=[('Home Renovation', 'Home Renovation'), ('Plumbing Services', 'Plumbing Services'), ('Painting & Decoration', 'Painting & Decoration'), ('Custom Cabinetry and Carpentry', 'Custom Cabinetry and Carpentry'), ('Flooring Installation', 'Flooring Installation'), ('Moving Services', 'Moving Services'), ('Demolition Services', 'Demolition Services'), ('Excavation', 'Excavation'), ('Architectural Design', 'Architectural Design'), ('Handyman Services', 'Handyman Services'), ('Gardening and Lawn Care', 'Gardening and Lawn Care'), ('Pool Maintenance', 'Pool Maintenance'), ('Home Organization', 'Home Organization')], max_length=100),
        ),
    ]
