# Generated by Django 5.0.3 on 2025-02-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_worker_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Payment Pending'), ('COMPLETED', 'Payment Completed'), ('FAILED', 'Payment Failed')], default='PENDING', max_length=20),
        ),
    ]
