# Generated by Django 5.1.3 on 2024-12-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hirepeople", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="logintable",
            new_name="logintable_info",
        ),
    ]
